- name: provision aws resources
  hosts: localhost
  remote_user: ubuntu
  vars:
    - region: us-west-2
    - bucket: telemetry-spark-emr-2

  tasks:
    - name: launch cloudformation
      cloudformation:
        stack_name: "telemetry-spark-cloudformation"
        state: "present"
        region: "us-west-2"
        disable_rollback: true
        template: "ansible/files/cloudformation.json"
        tags:
          type: "telemetry"
          application: "spark"
        template_parameters:
          TelemetryAnalysisCodeBucket: "{{telemetry_analysis_code_bucket}}"
          TelemetryAnalysisSparkEMRBucket: "{{telemetry_analysis_spark_emr_bucket}}"
          TelemetryAnalysisPublicBucket: "{{telemetry_analysis_public_bucket}}"
          TelemetryAnalysisPrivateBucket: "{{telemetry_analysis_private_bucket}}"
      register: cloudformation

    - name: create bucket
      s3: bucket={{bucket}} region={{region}} mode=create

    - name: copy EMR steps
      s3: bucket={{bucket}} region={{region}} object=steps/batch.sh src=ansible/files/batch.sh mode=put

    - name: copy EMR bootstrap script
      s3: bucket={{bucket}} region={{region}} object=bootstrap/telemetry.sh src=ansible/files/telemetry.sh mode=put

    - name: copy EMR configuration
      s3: bucket={{bucket}} region={{region}} object=configuration/configuration.json src=ansible/files/configuration.json mode=put permission=public-read

